<?php
Schema::create('example', function (Blueprint $table) {
    $table->bigIncrements('id');
    $table->bigInteger('big_integer_col');
    $table->binary('binary_col');
    $table->boolean('boolean_col');
    $table->char('char_col', 10);
    $table->date('date_col');
    $table->dateTime('date_time_col');
    $table->decimal('decimal_col', 8, 2);
    $table->double('double_col', 8, 2);
    $table->enum('enum_col', ['option1', 'option2', 'option3']);
    $table->float('float_col', 8, 2);
    $table->geometry('geometry_col');
    $table->geometryCollection('geometry_collection_col');
    $table->increments('increments_col');
    $table->integer('integer_col');
    $table->ipAddress('ip_address_col');
    $table->json('json_col');
    $table->jsonb('jsonb_col');
    $table->lineString('line_string_col');
    $table->longText('long_text_col');
    $table->macAddress('mac_address_col');
    $table->mediumIncrements('medium_increments_col');
    $table->mediumInteger('medium_integer_col');
    $table->mediumText('medium_text_col');
    $table->morphs('morphs_col');
    $table->multiLineString('multi_line_string_col');
    $table->multiPoint('multi_point_col');
    $table->multiPolygon('multi_polygon_col');
    $table->nullableTimestamps();
    $table->nullableUuidMorphs('nullable_uuid_morphs_col');
    $table->point('point_col');
    $table->polygon('polygon_col');
    $table->rememberToken();
    $table->set('set_col', ['option1', 'option2', 'option3']);
    $table->smallIncrements('small_increments_col');
    $table->smallInteger('small_integer_col');
    $table->softDeletes();
    $table->softDeletesTz();
    $table->string('string_col');
    $table->text('text_col');
    $table->time('time_col');
    $table->timeTz('time_tz_col');
    $table->timestamp('timestamp_col');
    $table->timestampTz('timestamp_tz_col');
    $table->timestamps();
    $table->timestampsTz();
    $table->tinyIncrements('tiny_increments_col');
    $table->tinyInteger('tiny_integer_col');
    $table->unsignedBigInteger('unsigned_big_integer_col');
    $table->unsignedDecimal('unsigned_decimal_col', 8, 2);
    $table->unsignedInteger('unsigned_integer_col');
    $table->unsignedMediumInteger('unsigned_medium_integer_col');
    $table->unsignedSmallInteger('unsigned_small_integer_col');
    $table->unsignedTinyInteger('unsigned_tiny_integer_col');
    $table->uuid('uuid_col');
    $table->uuidMorphs('uuid_morphs_col');
});
